"""Explicit-start DAgger training with quantization-aware exact teacher labels."""
import os
os.environ['PYTHONDONTWRITEBYTECODE']='1'
os.environ.setdefault('PYGAME_HIDE_SUPPORT_PROMPT','1')
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
import argparse,json
from dataclasses import dataclass,asdict,replace
from tools import train_targeted_dagger as targeted
from barrage_rl.quantized_teacher import install_collection_teacher,DEFAULT_CONFIG


@dataclass
class QuantizedTrainingConfig(targeted.TargetedConfig):
    teacher_plane_half_width_pixels: float = .5001
    teacher_bullet_half_width_pixels: float = .5001
    teacher_relative_half_width_pixels: float = 1.0002
    teacher_uncertainty_scenarios: int = 9
    teacher_uncertainty_layout: str = 'coherent_opposed_3x3'
    teacher_uncertainty_aggregation: str = 'maximum_action_cost'
    teacher_uncertainty_scope: str = 'rendered_pixel_quantization_only'


def load_config():
    data=asdict(targeted.load_config())
    data['output_dir']='runs/visual_set_v53'
    # A new run must allocate its own generated episode pools. Keep the explicit
    # targeted replay seed list, whose reuse is intentional in the collector.
    data['collection_seed']=None
    data['evaluation_seed']=None
    return QuantizedTrainingConfig(**data)


def validate_config(config):
    # The historical prepared validator expects integer seeds. Resolve only a
    # copy for preflight; the actual run allocates and records seeds at launch.
    checked=replace(config)
    targeted.training._resolve_run_seeds(checked)
    targeted.validate_config(checked)
    if config.teacher_kind!='exact' or not config.deployment_rgb_observation or config.collection_causal_action_delay_steps:
        raise ValueError('Quantized labels require exact teacher, RGB collection and zero action delay')
    expected=load_config()
    for key,value in asdict(expected).items():
        if key.startswith('teacher_uncertainty_') or key.endswith('half_width_pixels'):
            if getattr(config,key)!=value:
                raise ValueError(f'Unsupported quantization config: {key}')


def install_runtime():
    targeted.install_runtime()
    install_collection_teacher()
    training=targeted.training
    training._MANIFEST_SOURCE_FILES=tuple(dict.fromkeys((*training._MANIFEST_SOURCE_FILES,
        'barrage_rl/quantized_teacher.py','tools/train_quantized_dagger.py')))


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    group=parser.add_mutually_exclusive_group()
    group.add_argument('--plan',action='store_true')
    group.add_argument('--train',action='store_true')
    args=parser.parse_args()
    os.chdir(ROOT)
    config=load_config();validate_config(config)
    if not args.train:
        print(json.dumps(asdict(config),indent=2));return
    install_runtime()
    # Source snapshots and config are generated by the existing fresh-run path.
    # Historical targeted preflight describes different labels and is not reused.
    targeted.training.train_tracked_policy(config)


# Spawn imports the executable under __mp_main__; install before collection starts.
if __name__ in ('__main__','__mp_main__'):
    install_runtime()
if __name__=='__main__':main()
